export enum DebtStatus {
  UNASSIGNED = 'UNASSIGNED',
  ASSIGNED_OA = 'ASSIGNED_OA',
  ASSIGNED_AGENT = 'ASSIGNED_AGENT',
  IN_PROGRESS = 'IN_PROGRESS',
  APPOINTMENT_MADE = 'APPOINTMENT_MADE',
  PAID = 'PAID',
  CANCELED = 'CANCELED',
  EXPIRED = 'EXPIRED',
  ASSIGNED_SUP = 'ASSIGNED_SUP',
  ASSIGNED_USER = 'ASSIGNED_USER',
  PULLBACK = 'PULLBACK',
}
