export enum SettingTopic {
  'DEBT_CIF_GROUPING' = 'DEBT_CIF_GROUPING',
  'DEBT_ASSIGN_NEW_OA' = 'DEBT_ASSIGN_NEW_OA',
  'DEBT_EXPIRES_DAY' = 'DEBT_EXPIRES_DAY',
  'ASSIGNED_BY_BALANCE' = 'ASSIGNED_BY_BALANCE',
  'CURRENT_BATCH' = 'CURRENT_BATCH', // value: string
  'PREVIOUS_BATCH' = 'PREVIOUS_BATCH', // value: string
  'BATCH' = 'BATCH', // value: string[]
  'DEBT_ASSIGN_NEW_AGENT' = 'DEBT_ASSIGN_NEW_AGENT',
}
